### ISSUE TITLE
Registering the package

### ISSUE THREAD

**Issue by AtilaSaraiva** [AtilaSaraiva/SequentialCompression.jl#29]
@JuliaRegistrator register()

**Comment by milankl** [comment]
Do you anticipate to provide an interface for other compression libraries as well? Because at the moment the ZfpCompression.jl and our interface is hardcoded in (which is fine!) but then I would suggest to maybe rename this package to SequentialZfpCompression.jl? Otherwise users might be confused that it's not about *any* compression?

**Comment by milankl** [comment]
> @JuliaRegistrator register()

also you have to write `register` without `()`

**Comment by AtilaSaraiva** [comment]
Hey @milankl  I created another repo to avoid breaking the link to this one from the juliacon schedule. Here it is [https://github.com/AtilaSaraiva/SequentialZfpCompression.jl](https://github.com/AtilaSaraiva/SequentialZfpCompression.jl). I am archiving this one.
